CREACIÓN DE TENSORES 

In [2]:
import torch

# 1. Desde una lista de Python
tensor_lista = torch.tensor([[1, 2], [3, 4]])

# 2. Tensores de ceros, unos o aleatorios (muy útiles para inicializar pesos)
ceros = torch.zeros((2, 3))       # Matriz de 2 filas y 3 columnas llena de ceros
aleatorio = torch.randn((3, 3))   # Matriz 3x3 con distribución normal

print(f"Forma (shape) del tensor aleatorio: {aleatorio.shape}")
print(f"Tipo de dato: {aleatorio.dtype}")

Forma (shape) del tensor aleatorio: torch.Size([3, 3])
Tipo de dato: torch.float32


OPERACIONES MATEMÁTICAS

In [3]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[1, 1], [1, 1]])

# Suma elemento a elemento
suma = A + B 

# Multiplicación matricial (¡CRÍTICO EN REDES NEURONALES!)
# Se puede usar el operador @ o torch.matmul
mult_mat = A @ B

REDIMENSIONAMIENTO : RESHAPE/VIEW

In [4]:
# Tensor de 1 dimensión con 6 elementos
x = torch.tensor([1, 2, 3, 4, 5, 6])

# Cambiar la forma a una matriz de 2x3
x_matriz = x.view(2, 3) 
# También puedes usar x.reshape(2, 3)

# El -1 es un comodín muy usado en exámenes. Le dice a PyTorch: 
# "Calcula esta dimensión automáticamente en base a las demás".
x_auto = x.view(3, -1) # PyTorch sabe que el -1 debe ser un 2.

BASIQUITOS PARA APRENDER :

Ejercicio 1:Crea un tensor aleatorio X con dimensiones $(4, 3)$ usando una distribución normal.

Ejercicio 2:Crea un tensor de pesos W con dimensiones $(3, 2)$ lleno de unos. Luego, realiza la multiplicación matricial entre X y W. ¿Cuál será la dimensión (shape) del tensor resultante?

Ejercicio 3:Tienes un tensor T con dimensiones $(16, 8)$. ¿Qué línea de código usarías para "aplanarlo" (convertirlo en un tensor de una sola dimensión con todos sus elementos) utilizando el comodín -1?



In [5]:
random_tensor = torch.randn(4,3)
# si se usara rand pues seria numeros aleatorios con distribucion uniforme 
# pero en este caso queremos distribucion normal, por eso usamos randn
print(random_tensor)

tensor([[-1.3686, -0.1863, -1.4966],
        [-0.1863, -0.2397, -0.8230],
        [ 1.2459, -0.8930,  0.5119],
        [ 1.2389,  0.8102, -1.9247]])


In [13]:
#tensor_w = torch.tensor(3,2)
# esto equivale a crear un tensor con una dimension y con los valores 3 y 2 

# PAARA CREAR TENSORES CON UNA FORMA DETEMRMINADA SE USAN LAS FUNCIONES INTEGRADAS
# DE CEROS -> torch.zeros((3,2))
# DE UNOS -> torch.ones((3,2))
# DE NUMEROS ALEATORIOS -> torch.randn((3,2))
tensor_w = torch.ones(3,2)
print(tensor_w.shape)
print(tensor_w)
# para poder multiplicar acordarse de que a @ b -> a.shape[1] == b.shape[0]
# osea el numero de filas de a debe ser igual al numero de columnas de b

print(random_tensor @ tensor_w)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[-3.0514, -3.0514],
        [-1.2490, -1.2490],
        [ 0.8649,  0.8649],
        [ 0.1243,  0.1243]])


In [15]:
tensor_T = torch.randn(16,8)
tensor_T.reshape(1,-1)


tensor([[-3.8870e-01,  1.2927e+00, -2.8888e-01,  8.3791e-01,  1.0612e+00,
          1.7452e+00, -9.9237e-01, -2.2759e-01,  4.1257e-01,  3.1484e+00,
          1.4626e+00,  9.5303e-01, -1.2635e-02, -7.2978e-01, -3.2318e-02,
          3.5719e-01, -8.4780e-01, -1.3114e-02,  1.3410e+00,  1.7336e+00,
          1.2574e+00,  1.2895e+00,  1.5694e+00, -4.5476e-01, -1.3101e-01,
         -1.0003e+00,  1.8008e+00, -1.1704e+00, -1.1612e+00, -4.2769e-01,
         -1.6680e+00, -2.0842e-01, -1.2674e+00, -1.3848e+00, -5.0671e-01,
          8.5378e-01, -4.5940e-01,  8.5757e-01,  7.4045e-01, -3.0319e-01,
          7.3378e-01,  6.5825e-01,  8.5418e-02, -1.8820e-01, -8.5519e-01,
         -6.3305e-01, -4.3001e-02,  9.7021e-01, -9.3233e-01, -3.9876e-01,
         -7.2350e-01, -9.6275e-01, -4.9027e-01, -2.5391e-01,  4.3338e-01,
          2.8138e-01, -7.3974e-01, -1.6350e+00, -1.8199e-01, -1.2452e+00,
          1.5660e+00, -6.0125e-01,  1.2918e-01,  2.3455e-01,  7.7564e-02,
          2.5181e-01,  9.2600e-01, -1.